### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by superalino** [nextgrid/HackYeah2020#7]
so: Debian 10 
cpu: Ryzen 3700x
ram: 32 Gb
gpu: GTX1060 6 Gb

# nvidia-smi
Tue Sep 21 00:07:34 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.84       Driver Version: 460.84       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  On   | 00000000:08:00.0 Off |                  N/A |
| 37%   57C    P0    24W / 120W |     22MiB /  6077MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1472      G   /usr/lib/xorg/Xorg                 15MiB |
|    0   N/A  N/A      1785      G   /usr/bin/gnome-shell                4MiB |
+-----------------------------------------------------------------------------+

Inference with some images doesn't work.

# python3 detect.py --weights yolov5s.pt --conf 0.25 --source /dev/shm/799834/ --project /dev/shm/porcodio/

Unable to init server: Could not connect: Connection refused
Unable to init server: Impossibile connettersi: Connection refused

(detect.py:24881): Gdk-CRITICAL **: 00:05:26.480: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='/dev/shm/porcodio/', save_conf=False, save_txt=False, source='/dev/shm/799834/', update=False, view_img=False, weights=['yolov5s.pt'])
Using torch 1.7.1 CUDA:0 (GeForce GTX 1060 6GB, 6077MB)

Fusing layers...
Model Summary: 232 layers, 7459581 parameters, 0 gradients, 17.5 GFLOPS
image 1/52 /dev/shm/799834/secondo_10.38.jpg: 384x640 Done. (0.025s)
image 2/52 /dev/shm/799834/secondo_12.38.jpg: 384x640 Done. (0.023s)
image 3/52 /dev/shm/799834/secondo_2.41.jpg: 384x640 Done. (0.026s)
image 4/52 /dev/shm/799834/secondo_2.58.jpg: 384x640 Done. (0.027s)
image 5/52 /dev/shm/799834/secondo_2.69.jpg: 384x640 Done. (0.022s)
image 6/52 /dev/shm/799834/secondo_2.83.jpg: 384x640 Done. (0.021s)
image 7/52 /dev/shm/799834/secondo_22.17.jpg: 384x640 Done. (0.021s)
image 8/52 /dev/shm/799834/secondo_22.29.jpg: 384x640 Done. (0.023s)
image 9/52 /dev/shm/799834/secondo_22.41.jpg: 384x640 Done. (0.022s)
image 10/52 /dev/shm/799834/secondo_22.58.jpg: 384x640 Done. (0.030s)
image 11/52 /dev/shm/799834/secondo_22.7.jpg: 384x640 Done. (0.025s)
image 12/52 /dev/shm/799834/secondo_23.37.jpg: 384x640 Done. (0.027s)
image 13/52 /dev/shm/799834/secondo_23.49.jpg: 384x640 Done. (0.021s)
image 14/52 /dev/shm/799834/secondo_25.03.jpg: 384x640 Done. (0.020s)
image 15/52 /dev/shm/799834/secondo_25.18.jpg: 384x640 Done. (0.021s)
image 16/52 /dev/shm/799834/secondo_25.3.jpg: 384x640 Done. (0.021s)
image 17/52 /dev/shm/799834/secondo_25.42.jpg: 384x640 Done. (0.022s)
image 18/52 /dev/shm/799834/secondo_25.58.jpg: 384x640 Done. (0.022s)
image 19/52 /dev/shm/799834/secondo_25.7.jpg: 384x640 Done. (0.020s)
image 20/52 /dev/shm/799834/secondo_25.82.jpg: 384x640 Done. (0.020s)
image 21/52 /dev/shm/799834/secondo_25.94.jpg: 384x640 Done. (0.021s)
image 22/52 /dev/shm/799834/secondo_26.06.jpg: 384x640 Done. (0.020s)
image 23/52 /dev/shm/799834/secondo_26.18.jpg: 384x640 Done. (0.020s)
image 24/52 /dev/shm/799834/secondo_26.7.jpg: 384x640 Done. (0.021s)
image 25/52 /dev/shm/799834/secondo_26.83.jpg: 384x640 Done. (0.020s)
image 26/52 /dev/shm/799834/secondo_26.98.jpg: 384x640 Done. (0.021s)
image 27/52 /dev/shm/799834/secondo_27.09.jpg: 384x640 Done. (0.020s)
image 28/52 /dev/shm/799834/secondo_27.21.jpg: 384x640 Done. (0.020s)
image 29/52 /dev/shm/799834/secondo_27.37.jpg: 384x640 Done. (0.020s)
image 30/52 /dev/shm/799834/secondo_27.49.jpg: 384x640 1 wild boars, Done. (0.021s)
image 31/52 /dev/shm/799834/secondo_27.62.jpg: 384x640 Done. (0.020s)
image 32/52 /dev/shm/799834/secondo_27.78.jpg: 384x640 Done. (0.020s)
image 33/52 /dev/shm/799834/secondo_27.93.jpg: 384x640 Done. (0.020s)
image 34/52 /dev/shm/799834/secondo_28.05.jpg: 384x640 Done. (0.020s)
image 35/52 /dev/shm/799834/secondo_28.17.jpg: 384x640 Done. (0.020s)
image 36/52 /dev/shm/799834/secondo_28.29.jpg: 384x640 Done. (0.019s)
image 37/52 /dev/shm/799834/secondo_28.41.jpg: 384x640 Done. (0.020s)
image 38/52 /dev/shm/799834/secondo_28.51.jpg: 384x640 Done. (0.020s)
image 39/52 /dev/shm/799834/secondo_3.01.jpg: 384x640 Done. (0.019s)
image 40/52 /dev/shm/799834/secondo_3.13.jpg: 384x640 Done. (0.019s)
image 41/52 /dev/shm/799834/secondo_3.28.jpg: 384x640 Done. (0.019s)
image 42/52 /dev/shm/799834/secondo_3.37.jpg: 384x640 Done. (0.020s)
image 43/52 /dev/shm/799834/secondo_3.54.jpg: Traceback (most recent call last):
  File "detect.py", line 182, in <module>
    detect()
  File "detect.py", line 85, in detect
    tmp_pred = pred[0][torch.tensor(x)]
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by Mindgames** [comment]
Hi @superalino,  This was a hackathon project, however you can try the main now, did merge a old pull request, maybe that solves it.
